module.exports = {
  "last_item": null,
  "total_items": "9929",
  "first_item": null,
  "page_number": "1",
  "page_size": "10",
  "page_items": null,
  "search_time": "0.031",
  "page_count": "993",
  "events": {
    "event": [
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "PA",
        "postal_code": null,
        "going_count": null,
        "all_day": "0",
        "latitude": "39.8878",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/personal-shopping-prosp-/E0-001-101807482-2@2018090808?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-101807482-2@2018090808",
        "privacy": "1",
        "city_name": "Prospect Park",
        "link_count": null,
        "longitude": "-75.3086",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Pennsylvania",
        "start_time": "2018-09-08 08:30:00",
        "tz_id": null,
        "description": " <strong>Sponsored by:</strong> New Hope Community Ministries<br> <strong>Minimum age:</strong> 16<br> If you like to shop, Personal Shopping in Prospect Park is just the project for you! New Hope Community Ministries serves over 100 families a month through their mentoring and free grocery program.Volunteers are needed to interact with families by helping them sign in, “shopping” with them in th . . .",
        "modified": "2018-06-03 08:55:59",
        "venue_display": "0",
        "tz_country": null,
        "performers": null,
        "title": "Personal Shopping in Prospect Park",
        "venue_address": null,
        "geocode_type": "City Based GeoCodes",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2017-04-04 12:54:51",
        "venue_id": "V0-001-000185159-8",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Prospect Park, Pennsylvania, United States",
        "venue_url": "http://philadelphia.eventful.com/venues/prospect-park-pennsylvania-united-states-/V0-001-000185159-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "DE",
        "postal_code": "19801",
        "going_count": null,
        "all_day": "0",
        "latitude": "39.7245",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/volunteer-reader-/E0-001-115972366-3@2018082916?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-115972366-3@2018082916",
        "privacy": "1",
        "city_name": "Wilmington",
        "link_count": null,
        "longitude": "-75.5423",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Delaware",
        "start_time": "2018-08-29 16:30:00",
        "tz_id": null,
        "description": " <strong>Sponsored by:</strong> DHSS: Division for the Visually Impaired<br> <strong>Minimum age:</strong> 18<br> The Delaware Division for the Visually Impaired is currently looking for a volunteer to help a client in Dover, Delaware. The volunteer would be asked to read mail, newspapers, and other correspondents upon request of the client. The client is asking for volunteer help on either wednesdays or friday . . .",
        "modified": "2018-07-06 18:56:06",
        "venue_display": "0",
        "tz_country": null,
        "performers": null,
        "title": "Volunteer Reader",
        "venue_address": null,
        "geocode_type": "Zip Code Based GeoCodes",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2018-07-06 05:08:23",
        "venue_id": "V0-001-000131149-8",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Postal code 19801, US",
        "venue_url": "http://philadelphia.eventful.com/venues/postal-code-19801-us-/V0-001-000131149-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "DE",
        "postal_code": "19736",
        "going_count": null,
        "all_day": "0",
        "latitude": "39.7889",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/open-mic-preparations-/E0-001-111923570-0@2018092017?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-111923570-0@2018092017",
        "privacy": "1",
        "city_name": "Yorklyn",
        "link_count": null,
        "longitude": "-75.6503",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Delaware",
        "start_time": "2018-09-20 17:00:00",
        "tz_id": null,
        "description": " <strong>Sponsored by:</strong> Center for the Creative Arts<br> <strong>Minimum age:</strong> 18<br> Help us prepare for our monthly open mic night. Arrange tables and chairs, dress tables, organize beverages and paper goods. Must be able to lift a chair . . . . . .",
        "modified": "2018-02-22 12:09:29",
        "venue_display": "0",
        "tz_country": null,
        "performers": null,
        "title": "Open Mic Preparations",
        "venue_address": null,
        "geocode_type": "Zip Code Based GeoCodes",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2018-02-22 05:28:03",
        "venue_id": "V0-001-008697763-5",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Postal code 19736, United States",
        "venue_url": "http://philadelphia.eventful.com/venues/postal-code-19736-united-states-/V0-001-008697763-5?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "NJ",
        "postal_code": "08102",
        "going_count": null,
        "all_day": "0",
        "latitude": "39.9518",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/marketplace-camden-/E0-001-101800319-8@2018082810?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-101800319-8@2018082810",
        "privacy": "1",
        "city_name": "Camden",
        "link_count": null,
        "longitude": "-75.1177",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "New Jersey",
        "start_time": "2018-08-28 10:00:00",
        "tz_id": null,
        "description": " <strong>Sponsored by:</strong> TOUCH New Jersey, Inc.<br> <strong>Minimum age:</strong> 16<br> Touch New Jersey, Inc.’s mission is to help alleviate poverty by providing food and resources to individuals and families in need. Low Income families, senior citizens and individuals are invited to visit and stock-up on nutritional perishable and nonperishable food items once per week. Volunteers . . .",
        "modified": "2018-08-25 20:21:32",
        "venue_display": "0",
        "tz_country": null,
        "performers": null,
        "title": "Marketplace in Camden",
        "venue_address": null,
        "geocode_type": "Zip Code Based GeoCodes",
        "tz_olson_path": null,
        "recur_string": "on various days",
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2017-04-04 08:43:44",
        "venue_id": "V0-001-002907251-1",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Postal code 08102, United States",
        "venue_url": "http://philadelphia.eventful.com/venues/postal-code-08102-united-states-/V0-001-002907251-1?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "PA",
        "postal_code": "19104",
        "going_count": null,
        "all_day": "0",
        "latitude": "39.9576927",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/yoki-intergenerational-healing-/E0-001-116862815-7?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-116862815-7",
        "privacy": "1",
        "city_name": "Philadelphia",
        "link_count": null,
        "longitude": "-75.1926202",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Pennsylvania",
        "start_time": "2018-09-02 19:00:00",
        "tz_id": null,
        "description": " Loving Soul Yoga & Reiki Master Khadijah Renee present &quot;Yo-Ki Intergenerational Healing&quot;. An intergenerational Yoga & Reiki healing experience complete with a Healing Hut Pop-Up Shop.  Philadelphia-based yoga instructor, Jamilah MyAnn, and Shinpiden Reiki Master Teacher Khadijah Renee join creative forces to bring this unique group healing experience to young & old seekers of good health, light and love. Join us on Sunday, September 2nd (7-9pm), to relax with Reiki and find balance and harmony with Yoga at the Community Education Center (CEC) in the University City section of Philadelphia.  Personal investment: $15 Featured food and wellness vendors & healers TBA.  Reiki Master Khadijah “Renee’s” work is especially helpful to those suffering from depression and theloss of loved ones whether its via death, or divorce/separation. She first addresses re-focusing on thelove of self and then works to move outwards because without developing or healing our true love ofself, we can&#39;t effectively love others. A person-centered therapist. She feels the healthy individual can create healthy relationships across allsectors of life. She combines talk therapies with holistic healing modalities such as Reiki, CrystalHealing and Magnified Healing energies. A session with Khadijah is a wholesome experience thatfosters individual self-development. She has two offices near each other, one is more conducive to thepractice of Reiki. “I don&#39;t believe in long term therapy”. My goal is to foster your immediate healing sothat you feel better, and more able to handle life&#39;s challenges. ",
        "modified": "2018-08-07 17:33:55",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "Yo-Ki Intergenerational Healing",
        "venue_address": "3500 Lancaster Avenue",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": {
          "small": {
            "width": "48",
            "url": "//d1marr3m5x4iac.cloudfront.net/images/small/I0-001/041/013/784-1.jpeg_/yoki-intergenerational-healing-84.jpeg",
            "height": "48"
          },
          "width": "48",
          "caption": null,
          "medium": {
            "width": "128",
            "url": "//d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/041/013/784-1.jpeg_/yoki-intergenerational-healing-84.jpeg",
            "height": "128"
          },
          "url": "//d1marr3m5x4iac.cloudfront.net/images/small/I0-001/041/013/784-1.jpeg_/yoki-intergenerational-healing-84.jpeg",
          "thumb": {
            "width": "48",
            "url": "//d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/041/013/784-1.jpeg_/yoki-intergenerational-healing-84.jpeg",
            "height": "48"
          },
          "height": "48"
        },
        "created": "2018-08-07 17:33:55",
        "venue_id": "V0-001-000242533-6",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Community Education Center",
        "venue_url": "http://philadelphia.eventful.com/venues/community-education-center-/V0-001-000242533-6?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "PA",
        "postal_code": "19107",
        "going_count": null,
        "all_day": "0",
        "latitude": "39.9579669",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/working-conditions-opening-reception-/E0-001-117405825-2?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-117405825-2",
        "privacy": "1",
        "city_name": "Philadelphia",
        "link_count": null,
        "longitude": "-75.1592432",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Pennsylvania",
        "start_time": "2018-09-07 18:00:00",
        "tz_id": null,
        "description": "Working Conditions Opening Reception\nFeaturing: cinematic savage | CYJO | Rebecca Goldschmidt | Shizu Homma | Cynthia X. Hua | Sarah Khan | Tiffany Lin | Lewanda Lim | Lisa Pradhan | Shellie Zhang\nFriday, September 7, 6 – 8 p.m.\n\nExhibition runs September 4  – December 15, 2018\n\n \n\nAsian American lives are shaped by the concept of labor, whether working in factories overseas, as caretakers in the United States, or performing the emotional labor of smiling every time someone asks “Where are you from?”. The artists in Working Conditions utilize a variety of strategies—performance, video, painting, installation, sculpture, and mixed media—to illuminate the ways in which labor operates on a global and a personal level.\n\n \n\nThe opening reception will feature:\n\n \n\nPerformance by Rebecca Maria Goldschmidt\n\nIn the Filipino kitchen, vinegar is an omnipresent ingredient, but beyond its culinary value, it also serves as a medicinal and spiritual tool that has been essential to our survival. Nabanglo a lamisaan is an interactive installation inviting audiences to experience sukang ilocos, a sugarcane vinegar, and recall their own memories of bitterness, perseverance, and labor, as they learn about key historical events.\n\n \n\nPerformance by Shizu Homma\n\nReflecting on her personal labor history, Shizu Homma will perform traditional Japanese embroidery at the opening reception and additional performances during gallery hours and have finished needlework to frame. Visitors are invited to ask her about work she has done—illegal, legal, voluntary, coerced, paid, and unpaid. Homma’s performance will continue during gallery hours from September 10 – September 21.\n\n \n\nRelated Events:\n\nBeyond Appropriation: Economic Exploitation and Erasure – First Friday, October 5, 7 p.m.\n3:25pm performance by Gu Wei – First Friday, December 7, 7 p.m.\nThe Living Deal: API Poets on Loss, Labor, and Love – First Friday, November 2, 7 p.m.",
        "modified": "2018-08-24 12:02:13",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "Working Conditions Opening Reception",
        "venue_address": "1219 Vine Street",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "melissad58f1",
        "going": null,
        "country_abbr2": "US",
        "image": {
          "small": {
            "width": "48",
            "url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/040/999/932-4.png_/working-conditions-opening-reception-32.png",
            "height": "48"
          },
          "width": "48",
          "caption": null,
          "medium": {
            "width": "128",
            "url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/040/999/932-4.png_/working-conditions-opening-reception-32.png",
            "height": "128"
          },
          "url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/040/999/932-4.png_/working-conditions-opening-reception-32.png",
          "thumb": {
            "width": "48",
            "url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/040/999/932-4.png_/working-conditions-opening-reception-32.png",
            "height": "48"
          },
          "height": "48"
        },
        "created": "2018-08-24 12:02:13",
        "venue_id": "V0-001-001254336-7",
        "tz_city": null,
        "stop_time": "2018-09-07 20:00:00",
        "venue_name": "Asian Arts Initiative",
        "venue_url": "http://philadelphia.eventful.com/venues/asian-arts-initiative-/V0-001-001254336-7?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "DE",
        "postal_code": "19801",
        "going_count": null,
        "all_day": "0",
        "latitude": "39.7245",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/volunteer-shell-bagging-daysep-22nd-/E0-001-117394982-3?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-117394982-3",
        "privacy": "1",
        "city_name": "Wilmington",
        "link_count": null,
        "longitude": "-75.5423",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Delaware",
        "start_time": "2018-09-22 09:30:00",
        "tz_id": null,
        "description": " <strong>Sponsored by:</strong> Partnership for the Delaware Estuary<br> <strong>Minimum age:</strong> 13<br> Come celebrate National Estuaries Week by helping us bag oyster shell!We need your help! Every year more and more oyster shell is thrown away and hauled to landfills rather than returned to the water. Why might that be a big deal, you ask? Because baby oysters need those shells in order to grow big . . .",
        "modified": "2018-08-27 06:05:41",
        "venue_display": "0",
        "tz_country": null,
        "performers": null,
        "title": "Volunteer Shell Bagging Day-Sep 22nd",
        "venue_address": null,
        "geocode_type": "Zip Code Based GeoCodes",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2018-08-24 05:20:05",
        "venue_id": "V0-001-000131149-8",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Postal code 19801, US",
        "venue_url": "http://philadelphia.eventful.com/venues/postal-code-19801-us-/V0-001-000131149-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "PA",
        "postal_code": "19032",
        "going_count": null,
        "all_day": "0",
        "latitude": "39.8926",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/meal-pack-out-africa-september-philadelphia-pa-/E0-001-115873071-8?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-115873071-8",
        "privacy": "1",
        "city_name": "Folcroft",
        "link_count": null,
        "longitude": "-75.2785",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Pennsylvania",
        "start_time": "2018-09-15 11:00:00",
        "tz_id": null,
        "description": " <strong>Sponsored by:</strong> Islamic Relief USA<br> <strong>Minimum age:</strong> 13<br> On Saturday, September 15th, Islamic Relief USA and Rise Against Hunger will be joining forces to help combat hunger by helping assemble over 500,000 Meals for children suffering from hunger in AFRICA and around the world. The meals YOU package here, will help feed these children and their families . . .",
        "modified": "2018-07-13 04:37:29",
        "venue_display": "0",
        "tz_country": null,
        "performers": null,
        "title": "Meal Pack Out for Africa - September Philadelphia PA",
        "venue_address": null,
        "geocode_type": "Zip Code Based GeoCodes",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2018-07-02 05:50:21",
        "venue_id": "V0-001-000288492-8",
        "tz_city": null,
        "stop_time": null,
        "venue_name": "Postal code 19032, United States",
        "venue_url": "http://philadelphia.eventful.com/venues/postal-code-19032-united-states-/V0-001-000288492-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "PA",
        "postal_code": "19144",
        "going_count": null,
        "all_day": "2",
        "latitude": "40.0262263",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/september-17-drop-/E0-001-117423242-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-117423242-9",
        "privacy": "1",
        "city_name": "Philadelphia",
        "link_count": null,
        "longitude": "-75.1773979",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Pennsylvania",
        "start_time": "2018-09-17 00:00:00",
        "tz_id": null,
        "description": null,
        "modified": "2018-08-26 02:46:10",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "September 17 Drop in",
        "venue_address": "416 West Coulter Street",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2018-08-25 02:49:06",
        "venue_id": "V0-001-006118153-6",
        "tz_city": null,
        "stop_time": "2018-09-17 00:00:00",
        "venue_name": "The Funicular Railway Station",
        "venue_url": "http://philadelphia.eventful.com/venues/the-funicular-railway-station-/V0-001-006118153-6?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      },
      {
        "watching_count": null,
        "olson_path": "America/New_York",
        "calendar_count": null,
        "comment_count": null,
        "region_abbr": "PA",
        "postal_code": "19144",
        "going_count": null,
        "all_day": "2",
        "latitude": "40.0262263",
        "groups": null,
        "url": "http://philadelphia.eventful.com/events/february-12-drop-/E0-001-117419958-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
        "id": "E0-001-117419958-6",
        "privacy": "1",
        "city_name": "Philadelphia",
        "link_count": null,
        "longitude": "-75.1773979",
        "country_name": "United States",
        "country_abbr": "USA",
        "region_name": "Pennsylvania",
        "start_time": "2019-02-12 00:00:00",
        "tz_id": null,
        "description": null,
        "modified": "2018-08-26 01:36:12",
        "venue_display": "1",
        "tz_country": null,
        "performers": null,
        "title": "February 12 Drop in",
        "venue_address": "416 West Coulter Street",
        "geocode_type": "EVDB Geocoder",
        "tz_olson_path": null,
        "recur_string": null,
        "calendars": null,
        "owner": "evdb",
        "going": null,
        "country_abbr2": "US",
        "image": null,
        "created": "2018-08-25 01:53:00",
        "venue_id": "V0-001-006118153-6",
        "tz_city": null,
        "stop_time": "2019-02-12 00:00:00",
        "venue_name": "The Funicular Railway Station",
        "venue_url": "http://philadelphia.eventful.com/venues/the-funicular-railway-station-/V0-001-006118153-6?utm_source=apis&utm_medium=apim&utm_campaign=apic"
      }
    ]
  }
}